const { rejectAndRefund, reconcileRefund } = require('../../../utils/pay')
const STATUS_TEXT = { waiting_accept:'待接单', accepted:'已接单', preparing:'制作中', delivering:'配送中', completed:'已完成', rejected:'已拒单', refunded:'已退款', refunding:'退款中' }
const NEXT = { waiting_accept:{ text:'接单', status:'accepted' }, accepted:{ text:'开始制作', status:'preparing' }, preparing:{ text:'开始配送', status:'delivering' }, delivering:{ text:'完成订单', status:'completed' } }
Page({
  data:{ orderId:'', order:null, loading:true, busy:false, nextAction:null, refundActive:false },
  active:false,
  onLoad(options){ this.setData({ orderId:decodeURIComponent(options.orderId || '') }) },
  onShow(){ if(this.data.orderId){this.active=true;this.fetchOrder(true)} }, onHide(){ this.active=false;this.stopPolling() }, onUnload(){ this.active=false;this.stopPolling() },
  fetchOrder(reconcile=false){ this.setData({loading:!this.data.order}); return wx.cloud.callFunction({name:'merchantOrders',data:{action:'get',orderId:this.data.orderId}}).then((res)=>{const result=res.result||{};if(!result.success)throw new Error(result.message||'订单加载失败');const order=result.order;const refundActive=['requesting','processing'].includes(order.refundStatus);this.setData({order,loading:false,nextAction:NEXT[order.merchantStatus]||null,refundActive});this.schedulePolling();if(reconcile&&refundActive&&order.refundNo&&(!order.nextRefundQueryAt||new Date(order.nextRefundQueryAt).getTime()<=Date.now()))return reconcileRefund(order).catch((err)=>console.error('退款查单补偿失败',err)).then(()=>this.fetchOrder(false));return order}).catch((err)=>{this.setData({loading:false});wx.showToast({title:err.message||'加载失败',icon:'none'})}) },
  stopPolling(){if(this.timer){clearTimeout(this.timer);this.timer=null}}, schedulePolling(){this.stopPolling();if(this.active&&this.data.refundActive)this.timer=setTimeout(()=>this.fetchOrder(true),5000)},
  callCustomer(){const phone=this.data.order&&this.data.order.contactPhone;if(phone)wx.makePhoneCall({phoneNumber:phone});else wx.showToast({title:'订单未填写联系电话',icon:'none'})},
  updateStatus(){const action=this.data.nextAction,order=this.data.order;if(!action||!order||this.data.busy||this.data.refundActive)return;wx.showModal({title:action.text,content:'确认将订单更新为“'+STATUS_TEXT[action.status]+'”吗？',success:(modal)=>{if(!modal.confirm)return;this.setData({busy:true});wx.cloud.callFunction({name:'merchantOrders',data:{action:'updateStatus',orderId:order._id,nextStatus:action.status}}).then((res)=>{const result=res.result||{};if(!result.success)throw new Error(result.message||'状态更新失败');wx.showToast({title:action.text+'成功',icon:'success'});return this.fetchOrder()}).catch((err)=>wx.showToast({title:err.message||'更新失败',icon:'none'})).finally(()=>this.setData({busy:false}))}})},
  rejectOrder(){const order=this.data.order;if(!order||order.merchantStatus!=='waiting_accept'||this.data.busy||this.data.refundActive)return;wx.showModal({title:'拒单并退款',content:'确认拒绝该订单，并将全部实付款原路退还给用户吗？',confirmColor:'#d93026',success:(modal)=>{if(!modal.confirm)return;this.setData({busy:true});rejectAndRefund(order._id,'商家拒单').then(()=>{wx.showToast({title:'退款处理中',icon:'none'});return this.fetchOrder()}).catch((err)=>wx.showToast({title:err.message||'拒单失败',icon:'none'})).finally(()=>this.setData({busy:false}))}})}
})
